# VIAL 廃止（容量確保）
VIA_ENABLE = no
VIAL_ENABLE = no

# 有効化
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = no     # 自前実装を使用
MOUSEKEY_ENABLE = yes    # スクロール用（KC_WH_U/D）
EXTRAKEY_ENABLE = yes    # 音量キー用

# 無効化（容量節約）
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
