QMK_SETTINGS = yes

# --- 必要最小限 ---
VIA_ENABLE = no
VIAL_ENABLE = yes
LTO_ENABLE = yes
EEPROM_ENABLE = yes

# --- 重い/不要機能は全部OFF ---
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = no
MIDI_ENABLE = no
SLEEP_LED_ENABLE = no

# QMKの便利系も削る
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no          # 必要なら _LITE を yes に（それでも重ければ no のまま）
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
TAP_DANCE_ENABLE = no
LEADER_ENABLE = no
COMBO_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
KEY_OVERRIDE_ENABLE = no
CAPS_WORD_ENABLE = no
STENO_ENABLE = no
AUTOCORRECT_ENABLE = no
